const ALLOWED_IP_LIST_FOR_SEVENROOMS_WEBHOOK = [
    '*'
]

const ALLOWED_API_KEYS_FOR_WEBHOOKS = [
    '2209ed5a-7562-4539-9310-2dd063f8d98c'
]

module.exports = {
    ALLOWED_IP_LIST_FOR_SEVENROOMS_WEBHOOK,
    ALLOWED_API_KEYS_FOR_WEBHOOKS
}